### ISSUE TITLE
Go Modules Support

### ISSUE THREAD

**Issue by seoester** [KillingSpark/restic-cronned#10]
It would be great if restic-cronned would support Go Modules for improved dependency management and reproducible builds!

**Comment by KillingSpark** [comment]
It does now use go modules. I hope it works, I needed to do some replacing in go.mod for logrus to work properly. If you could try to build and report if it works i'll close this issue,

**Comment by KillingSpark** [comment]
I tested building on other systems, I'll mark this as closed
