### ISSUE TITLE
Consistent Naming of Commands

### ISSUE THREAD

**Issue by seoester** [KillingSpark/restic-cronned#6]
Currently, there are three commands defined in this repository:

 * `restic-cronned`
 * `rckeyutil`
 * `rc-commands`

Perhaps they could be renamed in a consistent manner.

**Comment by KillingSpark** [comment]
I restructured the repo, the src/cmd directory now contains rc-daemon rc-keyutil and rc-commands. When built with `go build` the binaries are named rc-*. I think that is consistent enough.

**Comment by seoester** [comment]
Very nice, thank you!
